Updated the routes.js with Prime check
IEEE-VIT/playing-with-numbers-node pull request #16
Opened 2020-09-30 19:23 UTC by HarshUdai

First contribution
I have added the logic of prime check, with the help of for loop and a count variable.

Thank you @ZiyanK

2020-09-30 21:19 UTC, ZiyanK requested changes
Logic looks good to go. I shall merge the code once these 2 changes are made

2020-09-30 21:19 UTC, ZiyanK commented on routes/routes.js
> +    }
Kindly shift the logic directly inside the route

2020-09-30 21:19 UTC, ZiyanK commented on routes/routes.js
> +    var num=req.params.num;
Assume the num variable to be inside the body of the request. Please make the necessary change for this.

2020-10-01 01:16 UTC, HarshUdai commented
Ok, I will shortly commit new changes.

2020-10-01 03:32 UTC, HarshUdai commented
Hey @ZiyanK  i have done the changes required.

2020-10-01 07:07 UTC, ZiyanK commented
Good job. Logic looks good. Kindly stick with the appropriate formatting in the future. I shall merge the pr :+1:

2020-10-01 07:07 UTC, merged

2020-10-01 07:12 UTC, HarshUdai commented
Thank you, @ZiyanK